dest_dir: "docs"
src_dir: "src"
app_name: "Onboarder Pro"
environments:

  dev:
    api_url: "http://localhost:3000"
    debug: true
    privateKeyFilePEM: "config/credentials/development/sbx_didkey_priv.pem"
    machineCredentialFile: "config/credentials/development/sbx_lear_credential_machine.txt"
    mydidkey: "did:key:zDnaeb3th2TDPrQTnM19Mdy543xFetwCpqjmcGBFgisqYKuL4"

    verifier:
      url: "https://verifier.dome-marketplace-sbx.org"
      token_endpoint: "https://verifier.dome-marketplace-sbx.org/oidc/token"
    issuer:
      credentialIssuancePath: "https://issuer.dome-marketplace-sbx.org/issuer-api/vci/v1/issuances/external"



  pre:
    api_url: "https://pre-api.example.com"
    debug: true
  pro:
    api_url: "https://api.example.com"
    debug: false