dest_dir: "docs"
src_dir: "src"
app_name: "Onboarding"



environments:

  dev:
    api_url: "http://localhost:3000"
    debug: true
    privateKeyFile: "config/credentials/development/sbx_didkey_priv.txt"
    machineCredentialFile: "config/credentials/development/sbx_lear_credential_machine.txt"
    mydidkey: "did:key:zDnaeajw3FmMgsGJxWggMLbXFgr7yoeTBKBsPAdErbLpSFLZt"

    verifier:
      url: "https://verifier.dome-marketplace-sbx.org"
      token_endpoint: "https://verifier.dome-marketplace-sbx.org/oidc/token"
    issuer:
      credentialIssuancePath: "https://issuer.dome-marketplace-sbx.org/vci/v1/issuances"

    smtp:
      enabled: true
      host: "smtp.ionos.de"
      port: 465
      tls: true
      username: "onboarding@dome-marketplace.eu"
      passwordFile: "config/credentials/production/prod_smtppassword.txt"


  pre:
    api_url: "https://pre-api.example.com"
    debug: true
  pro:
    api_url: "https://api.example.com"
    debug: false